"""Kibana dashboards-as-code guards.

The committed ``kibana/dashboards.ndjson`` is generated by
``scripts/build_dashboards.py``. These tests keep the artifact honest: it must
stay in sync with the builder, and its saved-object references must all resolve
(every dashboard panel -> a visualization, every visualization -> a data view).
"""

import json
from pathlib import Path

from scripts.build_dashboards import OUT, build

NDJSON = Path(__file__).parent.parent / "kibana" / "dashboards.ndjson"


def _committed() -> list[dict]:
    return [json.loads(line) for line in NDJSON.read_text().splitlines() if line.strip()]


def test_ndjson_in_sync_with_builder():
    # If this fails, re-run: python scripts/build_dashboards.py
    assert OUT == NDJSON
    assert _committed() == build()


def test_expected_objects_present():
    objects = _committed()
    by_type: dict[str, list[dict]] = {}
    for obj in objects:
        by_type.setdefault(obj["type"], []).append(obj)

    assert {o["id"] for o in by_type["index-pattern"]} == {"sws-events", "sws-alerts"}
    assert {o["id"] for o in by_type["dashboard"]} == {
        "sws-dashboard-overview",
        "sws-dashboard-geomagnetic",
        "sws-dashboard-solar",
        "sws-dashboard-health",
    }
    assert len(by_type["visualization"]) >= 12


def test_all_references_resolve():
    objects = _committed()
    ids = {(o["type"], o["id"]) for o in objects}
    for obj in objects:
        for ref in obj.get("references", []):
            assert (ref["type"], ref["id"]) in ids, f"{obj['id']} -> missing {ref}"


def test_dashboard_panels_match_references():
    by_id = {o["id"]: o for o in _committed()}
    for obj in by_id.values():
        if obj["type"] != "dashboard":
            continue
        ref_names = {r["name"] for r in obj["references"]}
        panels = json.loads(obj["attributes"]["panelsJSON"])
        assert panels, f"{obj['id']} has no panels"
        for panel in panels:
            assert panel["panelRefName"] in ref_names


def test_visualizations_reference_a_data_view():
    # every non-markdown visualization must point at one of our data views
    data_views = {"sws-events", "sws-alerts"}
    for obj in _committed():
        if obj["type"] != "visualization":
            continue
        vis_state = json.loads(obj["attributes"]["visState"])
        if vis_state["type"] == "markdown":
            assert obj["references"] == []
            continue
        dv_refs = [r for r in obj["references"] if r["type"] == "index-pattern"]
        assert len(dv_refs) == 1 and dv_refs[0]["id"] in data_views
